feat(vue3): migrate to vue3
nextcloud-libraries/nextcloud-dialogs pull request #884
Opened 2023-08-11 19:22 UTC by raimund-schluessler

2024-01-28 21:38 UTC, raimund-schluessler commented
@susnux I worked a bit on the migration, but I could use help with the Typescript stuff.

2024-01-31 16:06 UTC, susnux commented on lib/components/FilePicker/FilePickerBreadcrumbs.vue
> +					v-model:value="newNodeName"
We probably should rename this on `@nextcloud/vue` to `modelValue` and just use `v-model`, no?

2024-01-31 16:29 UTC, raimund-schluessler commented on lib/components/FilePicker/FilePickerBreadcrumbs.vue
> +					v-model:value="newNodeName"
It is already. It's a typo here.

2024-02-04 18:37 UTC, raimund-schluessler commented on lib/components/FilePicker/FilePickerBreadcrumbs.vue
> +					v-model:value="newNodeName"
Fixed.

2024-06-26 12:07 UTC, Antreesy commented
Hi @susnux!
i rebased the branch and tried to resolve conflicts from recent app changes. TSC and tests are failing, so I might have not done it correctly 🙈.
Could you double-check, when you have time?

2025-03-26 20:08 UTC, ShGKme commented
@raimund-schluessler I'll take over the PR to prepare the release soon, if it's ok

2025-03-26 21:16 UTC, raimund-schluessler commented
Great, please go ahead!

2025-04-03 20:22 UTC, st3iny requested changes
Seems to work otherwise.

2025-04-03 20:22 UTC, st3iny commented on lib/utils/dialogs.ts
>  			}),
AFAIK, this won't work in Vue 3. We can only pass `propsData` as the second argument. We need to find another workaround to wrap the onClose handler.

We also need to mount the component explicitly here.

## My proposed solution:

```js
	const vue = createApp(dialog, props)
	vue.mount(el)
```

2025-04-03 21:41 UTC, ShGKme commented on lib/utils/dialogs.ts
>  			}),
> We can only pass `propsData` as the second argument

This is true for `createApp().mount()`, not for `h`

Problem here is that props should be destructured.

2025-04-03 21:42 UTC, ShGKme commented on lib/utils/dialogs.ts
>  			}),
> We need to find another workaround to listen to the close event or simply remove the `onClose()` handler.

In Vue 3 event handlers always passed as `onEven` param.

`<comp @event="handler" />` is `h(comp, { onEvent: handler })`

2025-04-03 21:47 UTC, st3iny commented on lib/utils/dialogs.ts
>  			}),
TIL. I wasn't aware of the advanced features of `h`.

2025-04-03 21:56 UTC, susnux commented on lib/utils/dialogs.ts
>  			}),
for dialogs library this `createApp` is fine, but for nextcloud-vue it can cause unwanted behavior:
- it does not allow globally registered components in the dialog
- it does not allow to access registered pinia

Use case would be e.g. a settings store for dialog you spawn with API.

2025-05-02 15:38 UTC, closed without merging